src/Entity/Cheltuieli.php
<?php

namespace App\Entity;

use App\Repository\CheltuieliRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CheltuieliRepository::class)]
class Cheltuieli
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'cheltuielis')]
    private ?Comenzi $comanda = null;

    #[ORM\ManyToOne(inversedBy: 'cheltuielis')]
    private ?ComenziComunitare $comunitar = null;

    #[ORM\ManyToOne(inversedBy: 'cheltuielis')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CategoriiCheltuieli $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'cheltuielis')]
    private ?SubcategoriiCheltuieli $subcategorie = null;

    #[ORM\ManyToOne(inversedBy: 'cheltuielis')]
    private ?Consumabile $consumabil = null;

    #[ORM\Column]
    private ?float $suma = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $data_cheltuiala = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $descriere = null;

    #[ORM\Column(nullable: true)]
    private ?float $litri_motorina = null;

    #[ORM\Column(nullable: true)]
    private ?float $tva = null;

    #[ORM\Column(nullable: true)]
    private ?float $comision_tva = null;

    #[ORM\Column(nullable: true)]
    private ?float $comision_taxa_drum = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComanda(): ?Comenzi
    {
        return $this->comanda;
    }

    public function setComanda(?Comenzi $comanda): static
    {
        $this->comanda = $comanda;

        return $this;
    }

    public function getComunitar(): ?ComenziComunitare
    {
        return $this->comunitar;
    }

    public function setComunitar(?ComenziComunitare $comunitar): static
    {
        $this->comunitar = $comunitar;

        return $this;
    }

    public function getCategorie(): ?CategoriiCheltuieli
    {
        return $this->categorie;
    }

    public function setCategorie(?CategoriiCheltuieli $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getSubcategorie(): ?SubcategoriiCheltuieli
    {
        return $this->subcategorie;
    }

    public function setSubcategorie(?SubcategoriiCheltuieli $subcategorie): static
    {
        $this->subcategorie = $subcategorie;

        return $this;
    }

    public function getConsumabil(): ?Consumabile
    {
        return $this->consumabil;
    }

    public function setConsumabil(?Consumabile $consumabil): static
    {
        $this->consumabil = $consumabil;

        return $this;
    }

    public function getSuma(): ?float
    {
        return $this->suma;
    }

    public function setSuma(float $suma): static
    {
        $this->suma = $suma;

        return $this;
    }

    public function getDataCheltuiala(): ?\DateTimeInterface
    {
        return $this->data_cheltuiala;
    }

    public function setDataCheltuiala(\DateTimeInterface $data_cheltuiala): static
    {
        $this->data_cheltuiala = $data_cheltuiala;

        return $this;
    }

    public function getDescriere(): ?string
    {
        return $this->descriere;
    }

    public function setDescriere(?string $descriere): static
    {
        $this->descriere = $descriere;

        return $this;
    }

    public function getLitriMotorina(): ?float
    {
        return $this->litri_motorina;
    }

    public function setLitriMotorina(?float $litri_motorina): static
    {
        $this->litri_motorina = $litri_motorina;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(?float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getComisionTva(): ?float
    {
        return $this->comision_tva;
    }

    public function setComisionTva(?float $comision_tva): static
    {
        $this->comision_tva = $comision_tva;

        return $this;
    }

    public function getComisionTaxaDrum(): ?float
    {
        return $this->comision_taxa_drum;
    }

    public function setComisionTaxaDrum(?float $comision_taxa_drum): static
    {
        $this->comision_taxa_drum = $comision_taxa_drum;

        return $this;
    }
}

src/Entity/ComenziComunitare.php
<?php

namespace App\Entity;

use App\Repository\ComenziComunitareRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ComenziComunitareRepository::class)]
class ComenziComunitare
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comenziComunitares')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ParcAuto $nr_auto = null;

    #[ORM\Column(length: 20)]
    private ?string $nr_auto_snapshot = null;

    #[ORM\Column(length: 100)]
    private ?string $sofer = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $data_start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $data_stop = null;

    #[ORM\Column(nullable: true)]
    private ?float $nr_km = null;

    #[ORM\Column(nullable: true)]
    private ?float $profit = null;

    #[ORM\Column]
    private ?float $kg = null;

    #[ORM\Column]
    private ?float $pret = null;

    #[ORM\Column(length: 100)]
    private ?string $firma = null;

    /**
     * @var Collection<int, Cheltuieli>
     */
    #[ORM\OneToMany(targetEntity: Cheltuieli::class, mappedBy: 'comunitar', cascade: ['remove'])]
    private Collection $cheltuielis;

    #[ORM\Column(length: 100)]
    private ?string $remorca = null;

    #[ORM\Column]
    private ?bool $calculata = false;

    public function __construct()
    {
        $this->cheltuielis = new ArrayCollection();
        $this->calculata = false; 
    }


public function calculateAndSetProfit(): void
{
    $totalCheltuieli = 0;
    foreach ($this->cheltuielis as $cheltuiala) {
        $sumaBruta = $cheltuiala->getSuma();
        $tvaProcent = $cheltuiala->getTva() ?? 0;
        $comisionTvaProcent = $cheltuiala->getComisionTva() ?? 0;
        $comisionTaxaDrumProcent = $cheltuiala->getComisionTaxaDrum() ?? 0;
        
        // Comision taxa de drum = procent din suma bruta
        $comisionTaxaDrum = $sumaBruta * ($comisionTaxaDrumProcent / 100);
        
        $tvaValue = ($sumaBruta * $tvaProcent / (100 + $tvaProcent));
        $comisionTva = ($tvaValue * $comisionTvaProcent / 100);
        $cheltuialaNeta = $sumaBruta - $tvaValue + $comisionTva + $comisionTaxaDrum;
        
        $totalCheltuieli += $cheltuialaNeta;
    }
    
    $profit = $this->pret - $totalCheltuieli;
    $this->setProfit($profit);
}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNrAuto(): ?ParcAuto
    {
        return $this->nr_auto;
    }

    public function setNrAuto(?ParcAuto $nr_auto): static
    {
        $this->nr_auto = $nr_auto;

        return $this;
    }

    public function getNrAutoSnapshot(): ?string
    {
        return $this->nr_auto_snapshot;
    }

    public function setNrAutoSnapshot(string $nr_auto_snapshot): static
    {
        $this->nr_auto_snapshot = $nr_auto_snapshot;

        return $this;
    }

    public function getSofer(): ?string
    {
        return $this->sofer;
    }

    public function setSofer(string $sofer): static
    {
        $this->sofer = $sofer;

        return $this;
    }

    public function getDataStart(): ?\DateTimeInterface
    {
        return $this->data_start;
    }

    public function setDataStart(\DateTimeInterface $data_start): static
    {
        $this->data_start = $data_start;

        return $this;
    }

    public function getDataStop(): ?\DateTimeInterface
    {
        return $this->data_stop;
    }

    public function setDataStop(?\DateTimeInterface $data_stop): static
    {
        $this->data_stop = $data_stop;

        return $this;
    }

    public function getNrKm(): ?float
    {
        return $this->nr_km;
    }

    public function setNrKm(?float $nr_km): static
    {
        $this->nr_km = $nr_km;

        return $this;
    }

    public function getProfit(): ?float
    {
        return $this->profit;
    }

    public function setProfit(?float $profit): static
    {
        $this->profit = $profit;

        return $this;
    }

    public function getKg(): ?float
    {
        return $this->kg;
    }

    public function setKg(float $kg): static
    {
        $this->kg = $kg;

        return $this;
    }

    public function getPret(): ?float
    {
        return $this->pret;
    }

    public function setPret(float $pret): static
    {
        $this->pret = $pret;

        return $this;
    }

    public function getFirma(): ?string
    {
        return $this->firma;
    }

    public function setFirma(string $firma): static
    {
        $this->firma = $firma;

        return $this;
    }

    /**
     * @return Collection<int, Cheltuieli>
     */
    public function getCheltuielis(): Collection
    {
        return $this->cheltuielis;
    }

    public function addCheltuieli(Cheltuieli $cheltuieli): static
    {
        if (!$this->cheltuielis->contains($cheltuieli)) {
            $this->cheltuielis->add($cheltuieli);
            $cheltuieli->setComunitar($this);
        }

        return $this;
    }

    public function removeCheltuieli(Cheltuieli $cheltuieli): static
    {
        if ($this->cheltuielis->removeElement($cheltuieli)) {
            // set the owning side to null (unless already changed)
            if ($cheltuieli->getComunitar() === $this) {
                $cheltuieli->setComunitar(null);
            }
        }

        return $this;
    }

    public function getRemorca(): ?string
    {
        return $this->remorca;
    }

    public function setRemorca(string $remorca): static
    {
        $this->remorca = $remorca;

        return $this;
    }

    public function isCalculata(): ?bool
    {
        return $this->calculata;
    }

    public function setCalculata(bool $calculata): static
    {
        $this->calculata = $calculata;

        return $this;
    }
}

src/Form/ComenziComunitareType.php
<?php

namespace App\Form;

use App\Entity\ComenziComunitare;
use App\Entity\ParcAuto;
use App\Repository\ParcAutoRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;

class ComenziComunitareType extends AbstractType
{
    private $parcAutoRepository;

    public function __construct(ParcAutoRepository $parcAutoRepository)
    {
        $this->parcAutoRepository = $parcAutoRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nr_auto', TextType::class, [
                'label' => 'Mașină (Nr. Înmatriculare)',
                'mapped' => false,
                'attr' => [
                    'list' => 'parc_auto_list',
                    'autocomplete' => 'off',
                ],
            ])
            ->add('remorca', TextType::class, [
                'label' => 'Remorcă (Nr. Înmatriculare)',
                'required' => false,
                'attr' => [
                    'list' => 'remorca_list',
                    'autocomplete' => 'off',
                ],
            ])
            ->add('sofer', TextType::class, ['label' => 'Șofer'])
            ->add('data_start', DateType::class, [
                'label' => 'Data Start',
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker'],
                'format' => 'dd/MM/yyyy',
                'html5' => false,
            ])
            ->add('data_stop', DateType::class, [
                'label' => 'Data Stop',
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker'],
                'format' => 'dd/MM/yyyy',
                'html5' => false,
                'required' => false,
            ])
            ->add('nr_km', NumberType::class, [
                'label' => 'Număr KM',
                'required' => false,
            ])
            ->add('kg', NumberType::class, ['label' => 'Tone'])
            ->add('pret', NumberType::class, ['label' => 'Preț'])
            ->add('firma', TextType::class, ['label' => 'Firmă'])
        ;

        $builder->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) {
                $form = $event->getForm();
                $comanda = $event->getData();
                $nrAuto = $form->get('nr_auto')->getData();

                if ($nrAuto) {
                    $parcAuto = $this->parcAutoRepository->findOneBy(['nrAuto' => $nrAuto]);
                    if ($parcAuto) {
                        $comanda->setNrAuto($parcAuto);
                        $comanda->setNrAutoSnapshot($nrAuto);
                    }
                }
            }
        );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ComenziComunitare::class,
        ]);
    }
}

templates/comenzi_comunitare/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editează Comandă Comunitară{% endblock %}

{% block body %}
    <div class="form-container shadow-sm rounded-3 bg-white p-4" style="max-width: 600px; margin: 0 auto;">
        <h1 class="text-center mb-4">Editează Comandă Comunitară</h1>
        {{ form_start(form) }}
            <div class="row g-3">
                <div class="col-md-6">
                    {{ form_label(form.nr_auto) }}
                    {{ form_widget(form.nr_auto, {'attr': {'class': 'form-control', 'list': 'parc_auto_list'}}) }}
                    <datalist id="parc_auto_list">
                        {% for parc_auto in parc_auto_list %}
                            <option value="{{ parc_auto.nrAuto }}">{{ parc_auto.nrAuto }}</option>
                        {% endfor %}
                    </datalist>
                </div>
                <div class="col-md-6">
                    {{ form_label(form.remorca) }}
                    {{ form_widget(form.remorca, {'attr': {'class': 'form-control', 'list': 'remorca_list'}}) }}
                    <datalist id="remorca_list">
                        {% for remorca in parc_auto_list %}
                            <option value="{{ remorca.nrAuto }}">{{ remorca.nrAuto }}</option>
                        {% endfor %}
                    </datalist>
                </div>
                <div class="col-md-6">
                    {{ form_label(form.sofer) }}
                    {{ form_widget(form.sofer, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.data_start) }}
                    {{ form_widget(form.data_start, {'attr': {'class': 'form-control datepicker'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.data_stop) }}
                    {{ form_widget(form.data_stop, {'attr': {'class': 'form-control datepicker'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.nr_km) }}
                    {{ form_widget(form.nr_km, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.kg) }}
                    {{ form_widget(form.kg, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.pret) }}
                    {{ form_widget(form.pret, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.firma) }}
                    {{ form_widget(form.firma, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="button-group mt-4 d-flex justify-content-between">
                <a href="{{ path('app_comenzi_comunitare_index') }}" class="btn btn-secondary">Anulează</a>
                <button type="submit" class="btn btn-primary">Salvează</button>
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/comenzi_comunitare/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista Comenzi Comunitare{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .bg-light-green {
            background-color: rgba(0, 255, 0, 0.1);
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Lista Comenzi Comunitare</h1>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <form method="get" class="mb-3">
        <div class="input-group">
            <input type="text" name="start_date" class="form-control datepicker" placeholder="Data start (dd/mm/yyyy)" value="{{ start_date ?? '' }}">
            <button type="submit" class="btn btn-primary">Filtrează</button>
            <a href="{{ path('app_comenzi_comunitare_index') }}" class="btn btn-secondary">Resetează</a>
        </div>
    </form>

    <a href="{{ path('app_comenzi_comunitare_new') }}" class="btn btn-primary mb-3">Adaugă Comandă Comunitară</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Calculată</th>
                <th>Mașină</th>
                <th>Șofer</th>
                <th>Data Start</th>
                <th>Data Stop</th>
                <th>Număr Zile</th>
                <th>Număr Km</th>
                <th>Consum (l/100km)</th>
                <th>Profit</th>
                <th>Tone</th>
                <th>Preț</th>
                <th>Firmă</th>
                <th>Acțiuni</th>
            </tr>
        </thead>
        <tbody>
            {% for comenzi_comunitare in pagination %}
                <tr class="{% if comenzi_comunitare.calculata %}bg-light-green{% endif %}">
                    <td>
                        <input type="checkbox" class="calculata-checkbox" data-id="{{ comenzi_comunitare.id }}" {% if comenzi_comunitare.calculata %}checked{% endif %}>
                    </td>
                    <td>
                        <a href="{{ path('app_comenzi_comunitare_show', {'id': comenzi_comunitare.id}) }}">
                            {{ comenzi_comunitare.nrAutoSnapshot ?: 'N/A' }}
                        </a>
                    </td>
                    <td>{{ comenzi_comunitare.sofer }}</td>
                    <td>{{ comenzi_comunitare.dataStart ? comenzi_comunitare.dataStart|date('d/m/Y') : '-' }}</td>
                    <td>{{ comenzi_comunitare.dataStop ? comenzi_comunitare.dataStop|date('d/m/Y') : '-' }}</td>
                    <td>
                        {% if comenzi_comunitare.dataStart and comenzi_comunitare.dataStop %}
                            {{ ((comenzi_comunitare.dataStop|date('U') - comenzi_comunitare.dataStart|date('U')) / 86400 + 1)|round(0, 'floor') }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>{{ comenzi_comunitare.nrKm is not null ? comenzi_comunitare.nrKm : '-' }}</td>
                    <td>
                        {% set totalLitriMotorina = 0 %}
                        {% for cheltuiala in comenzi_comunitare.cheltuielis %}
                            {% set categorieNume = cheltuiala.categorie ? cheltuiala.categorie.nume|lower : '' %}
                            {% set subcategorieNume = cheltuiala.subcategorie ? cheltuiala.subcategorie.nume|lower : '' %}
                            {% if 'motorina' in categorieNume or 'motorina' in subcategorieNume %}
                                {% set totalLitriMotorina = totalLitriMotorina + (cheltuiala.litriMotorina ?: 0) %}
                            {% endif %}
                        {% endfor %}
                        {% if comenzi_comunitare.nrKm is not null and comenzi_comunitare.nrKm > 0 and totalLitriMotorina > 0 %}
                            {% set consumPer100Km = (totalLitriMotorina / comenzi_comunitare.nrKm * 100)|round(1) %}
                            {{ consumPer100Km|number_format(1, ',', '.') }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>{{ comenzi_comunitare.profit is not null ? comenzi_comunitare.profit|round : '-' }}</td>
                    <td>{{ comenzi_comunitare.kg }}</td>
                    <td>{{ comenzi_comunitare.pret }}</td>
                    <td>{{ comenzi_comunitare.firma }}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton-{{ comenzi_comunitare.id }}" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots-vertical"></i>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-{{ comenzi_comunitare.id }}">
                                <li><a class="dropdown-item text-warning" href="{{ path('app_comenzi_comunitare_edit', {'id': comenzi_comunitare.id}) }}">Editează</a></li>
                                <li>
                                    <form method="post" action="{{ path('app_comenzi_comunitare_delete', {'id': comenzi_comunitare.id}) }}" onsubmit="return confirm('Ești sigur că vrei să ștergi această comandă?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comenzi_comunitare.id) }}">
                                        <button type="submit" class="dropdown-item text-danger">Șterge</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="13">Nu există înregistrări.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="navigation mt-3 d-flex justify-content-center">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Funcționalitate pentru Calculată
            let processedCalculata = false;
            document.querySelectorAll('.calculata-checkbox').forEach(function(checkbox) {
                checkbox.addEventListener('change', function(e) {
                    if (processedCalculata) return;
                    processedCalculata = true;

                    var id = this.getAttribute('data-id');
                    var calculata = this.checked;
                    var url = '{{ path('app_comenzi_comunitare_update_calculata', {'id': 'ID'}) }}'.replace('ID', id);

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                            'X-Requested-With': 'XMLHttpRequest',
                        },
                        body: 'calculata=' + encodeURIComponent(calculata)
                    })
                    .then(response => {
                        if (!response.ok) throw new Error('Eroare server');
                        return response.json();
                    })
                    .then(data => {
                        if (data.success) {
                            console.log('Stare Calculată actualizată');
                            var row = checkbox.closest('tr');
                            if (calculata) {
                                row.classList.add('bg-light-green');
                            } else {
                                row.classList.remove('bg-light-green');
                            }
                        } else {
                            alert('Eroare: ' + (data.error || 'Răspuns neașteptat'));
                        }
                    })
                    .catch(error => {
                        console.error('Eroare:', error);
                        alert('Eroare la actualizare Calculată');
                    })
                    .finally(() => {
                        processedCalculata = false;
                    });
                });
            });
        });
    </script>
{% endblock %}

templates/comenzi_comunitare/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adaugă Comandă Comunitară{% endblock %}

{% block body %}
    <div class="form-container shadow-sm rounded-3 bg-white p-4" style="max-width: 600px; margin: 0 auto;">
        <h1 class="text-center mb-4">Adaugă Comandă Comunitară</h1>
        {{ form_start(form) }}
            <div class="row g-3">
                <div class="col-md-6">
                    {{ form_label(form.nr_auto) }}
                    {{ form_widget(form.nr_auto, {'attr': {'class': 'form-control', 'list': 'parc_auto_list'}}) }}
                    <datalist id="parc_auto_list">
                        {% for parc_auto in parc_auto_list %}
                            <option value="{{ parc_auto.nrAuto }}">{{ parc_auto.nrAuto }}</option>
                        {% endfor %}
                    </datalist>
                </div>
                <div class="col-md-6">
                    {{ form_label(form.remorca) }}
                    {{ form_widget(form.remorca, {'attr': {'class': 'form-control', 'list': 'remorca_list'}}) }}
                    <datalist id="remorca_list">
                        {% for remorca in parc_auto_list %}
                            <option value="{{ remorca.nrAuto }}">{{ remorca.nrAuto }}</option>
                        {% endfor %}
                    </datalist>
                </div>
                <div class="col-md-6">
                    {{ form_label(form.sofer) }}
                    {{ form_widget(form.sofer, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.data_start) }}
                    {{ form_widget(form.data_start, {'attr': {'class': 'form-control datepicker'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.data_stop) }}
                    {{ form_widget(form.data_stop, {'attr': {'class': 'form-control datepicker'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.nr_km) }}
                    {{ form_widget(form.nr_km, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.kg) }}
                    {{ form_widget(form.kg, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.pret) }}
                    {{ form_widget(form.pret, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="col-md-6">
                    {{ form_label(form.firma) }}
                    {{ form_widget(form.firma, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="button-group mt-4 d-flex justify-content-between">
                <a href="{{ path('app_comenzi_comunitare_index') }}" class="btn btn-secondary">Anulează</a>
                <button type="submit" class="btn btn-primary">Salvează</button>
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}